print ("Here is hello world in lots of languages") 
print  ("English", "Hello, World!"),
print ("Spanish", "¡Hola, Mundo!"),
print ("French", "Bonjour, le monde!"),
print("German", "Hallo, Welt!"),
print("Italian", "Ciao, Mondo!"),
print ("Portuguese", "Olá, Mundo!"),
print ("Dutch", "Hallo, Wereld!"),
print  ("Russian", "Привет, мир!"),
print  ("Chinese", "你好，世界！"),
print  ("Japanese", "こんにちは、世界！"),
print("Korean", "안녕하세요, 세계!"),
print ("Arabic", "مرحبا بالعالم!"),
print ("Hindi", "नमस्ते दुनिया!"),
